# Generated by Django 4.2.2 on 2023-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
