# Generated by Django 4.2.2 on 2023-09-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='category',
            new_name='user',
        ),
    ]
