# Generated by Django 4.2.2 on 2023-10-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0004_menuitem_featured_order_orderitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='featured',
        ),
    ]
